name: fiddle
on: 
  push:
    paths-ignore: # ignore if only npm stack-output or package changed
      - 'npm/*-stack-output.json'
      - 'npm/package.json'
jobs:
  fiddle-job:
    if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
    runs-on: ubuntu-latest
    env:
      DEV_PUBLISH_ENDPOINT: https://6klsawe709.execute-api.eu-central-1.amazonaws.com
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - run: echo "${{ github.ref }}"
      - name: set env vars
        id: localenv
        run: |
          BRANCH=$(git branch --show-current)
          echo "::set-output name=branch::$BRANCH"
          if [[ $BRANCH == 'master' ]]; then
            echo "we are on MASTER branch"
            echo "::set-output name=STAGE::prod"
          else 
            echo "we are on DEV branch"
            echo "::set-output name=STAGE::dev"
          fi
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json

      - name: Publish dependencies
        uses: indiesdev/curl@v1
        with:
          url: ${{ env.DEV_PUBLISH_ENDPOINT }}
          method: PUT
          headers: '{ "Content-Type": "application/json", "Authorization": "Basic the-most-important-Th!ng-in-life-is-2-not-take-yourself-2oo-Seriously" }'
          body: '{ 
            "ownerName": "${{ github.repository }}", 
            "stage": "dev", 
            "pack": ${{ steps.package.outputs.content }}
            }'
          timeout: 5000
  next-job:
    needs: fiddle-job
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "we are here!"