name: fiddle
on: 
  push:
    paths-ignore: # ignore if only npm stack-output or package changed
      - 'npm/*-stack-output.json'
      - 'npm/package.json'
jobs:
  fiddle-job:
    if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - run: echo "${{ github.ref }}"
      - name: set env vars
        id: localenv
        run: |
          BRANCH=$(git branch --show-current)
          echo "::set-output name=branch::$BRANCH"
          if [[ $BRANCH == 'master' ]]; then
            echo "we are on MASTER branch"
            echo "::set-output name=STAGE::prod"
          else 
            echo "we are on DEV branch"
            echo "::set-output name=STAGE::dev"
          fi
  next-job:
    needs: fiddle-job
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "we are here!"