name: fiddle
on: [push]
jobs:
  fiddle-job:
    runs-on: ubuntu-latest
    env:
      SOMEVAR: true
      NPM_FOLDER: npm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: check if npm folder exists
        run: |
          if test -e "${{ env.NPM_FOLDER }}"; then
            echo "NPM_EXISTS=true" >> $GITHUB_ENV
            echo "npm folder exists"
          else
            echo "NPM_EXISTS=false" >> $GITHUB_ENV
            echo "no npm folder here"
          fi
      - name: reading new env var only in a next step
        run: echo "the flag is ${{ env.NPM_EXISTS }}"
      - name: set env vars for deployment
        run: |
          if [[ ${{ github.ref }} =~ '/dev' ]]; then
            echo "we are on DEV branch"
            echo "DEPLOY=true" >> $GITHUB_ENV
            echo "STAGE=dev" >> $GITHUB_ENV
            echo "PUBLISH_ENDPOINT=${{ env.DEV_PUBLISH_ENDPOINT }}" >> $GITHUB_ENV
          else 
            if [[ ${{ github.ref }} =~ '/master' ]]; then
              echo "we are on MASTER branch"
              echo "DEPLOY=true" >> $GITHUB_ENV
              echo "STAGE=prod" >> $GITHUB_ENV
              echo "PUBLISH_ENDPOINT=${{ env.PROD_PUBLISH_ENDPOINT }}" >> $GITHUB_ENV
            else
              echo "we are on another branch"
              echo "DEPLOY=false" >> $GITHUB_ENV
            fi
          fi
      - name: conditional run
        if: env.NPM_EXISTS
        run: |
          cd npm
          npm publish