name: fiddle
on: [push]
jobs:
  fiddle-job:
    runs-on: ubuntu-latest
    env:
      SOMEVAR: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: fiddles
        run: |
          if ${SOMEVAR} == true; then
            echo "myflag=true" >> $GITHUB_ENV
            echo "flag set to true"
          else
            echo "myflag=false" >> $GITHUB_ENV
            echo "flag set to false"
          fi
          echo "the flag is ${{ env.myflag }}"