name: fiddle
on: [push]
jobs:
  fiddle-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - name: set env vars
        id: localenv
        run: |
          BRANCH=$(git branch --show-current)
          echo "::set-output name=branch::$BRANCH"
          if [[ $BRANCH == 'master' ]]; then
            echo "we are on MASTER branch"
            echo "::set-output name=STAGE::prod"
          else 
            echo "we are on DEV branch"
            echo "::set-output name=STAGE::dev"
          fi
      - name: set npm exists
        id: npm
        run: |
          if test -e "${{ env.NPM_FOLDER }}"; then
            echo "npm folder exists"
            echo "::set-output name=EXISTS::true"
          else
            echo "no npm folder here"
            echo "::set-output name=EXISTS::false"
          fi
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json
      - name: PRINT stuff
        run: |
          STAGE=${{ steps.localenv.outputs.STAGE }}
          echo ${{ steps.npm.outputs.EXISTS }}
          echo $STAGE
          echo ${{ steps.package.outputs.content.name }}