name: fiddle
on: 
  push:
    paths-ignore: # ignore if only npm stuff changed again
      - 'npm/*-stack-output.json'
      - 'npm/package.json'
jobs:
  check-secrets:
    if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
    runs-on: ubuntu-latest
    outputs:
      something: ${{ steps.step1.outputs.EXIST }}
    env:
      MY_SECRET: ${{ secrets.MY_SECRET}}
      MY_SECRET2: ${{ secrets.MY_SECRET2}}
    steps:
      - id: step1
        if: (env.MY_SECRET && env.MY_SECRET2)
        run: echo "::set-output name=EXIST::yes"
      - run: echo "${{ steps.step1.outputs.EXIST }}"
          
  fiddle-job:
    needs: check-secrets
    if: (needs.check-secrets.outputs.EXIST == 'yes')
    runs-on: ubuntu-latest
    env:
      DEV_PUBLISH_ENDPOINT: https://6klsawe709.execute-api.eu-central-1.amazonaws.com
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - run: echo "output was '${{ needs.check-secrets.outputs.something }}'"
      - name: set env vars
        id: localenv
        run: |
          BRANCH=$(git branch --show-current)
          echo "::set-output name=branch::$BRANCH"
          if [[ $BRANCH == 'master' ]]; then
            echo "we are on MASTER branch"
            echo "::set-output name=STAGE::prod"
          else 
            echo "we are on DEV branch"
            echo "::set-output name=STAGE::dev"
          fi
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json

  next-job:
    needs: fiddle-job
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "we are here!"