name: fiddle
on: [push]
jobs:
  fiddle-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - name: set env vars
        id: localenv
        run: |
          BRANCH=$(git branch --show-current)
          echo "::set-output name=branch::$BRANCH"
          if [[ $BRANCH == 'master' ]]; then
            echo "we are on MASTER branch"
            echo "::set-output name=STAGE::prod"
          else 
            echo "we are on DEV branch"
            echo "::set-output name=STAGE::dev"
          fi
      - name: set npm exists
        id: npm
        run: |
          if test -e "${{ env.NPM_FOLDER }}"; then
            echo "npm folder exists"
            echo "::set-output name=EXISTS::true"
          else
            echo "no npm folder here"
            echo "::set-output name=EXISTS::false"
          fi
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json
      - name: switch to hotfix branch
        id: branch
        run: |
          BRANCH=$(git branch --show-current)
          echo "::set-output name=BRANCH::$BRANCH"
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          if git show-ref --quiet refs/heads/$BRANCH-workflow-auto-hotfix; then
            git checkout $BRANCH-workflow-auto-hotfix
            git merge $BRANCH -m "auto merge from deploy workflow"
          else
            git checkout -b $BRANCH-workflow-auto-hotfix
          fi
          git branch
      - name: PRINT stuff
        run: |
          STAGE=${{ steps.localenv.outputs.STAGE }}
          echo ${{ steps.npm.outputs.EXISTS }}
          echo $STAGE
          echo $(basename -s .git $(git remote get-url origin))
          git branch
      - name: Add all changes and check if we need to commit files
        id: commit
        shell: bash
        run: |
          echo "dinges" >> myfile.txt
          git add --all
          if [-z "$(git status --porcelain)"]; then
            echo "::set-output name=PUSH::false"
          else
            git commit -m "auto push from workflow run"
            echo "::set-output name=PUSH::true"
          fi
      - name: Push changes
        if: steps.commit.outputs.PUSH == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create pull request
        if: steps.commit.outputs.PUSH == 'true'
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ steps.commit.outputs.BRANCH }}
          pr_title: "Pulling ${{ github.ref }} into ${{ steps.branch.outputs.BRANCH }}"
          pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          pr_draft: true                                    # Creates pull request as draft
          github_token: ${{ secrets.GITHUB_TOKEN }}
